source 'https://rubygems.org'

gem 'sinatra',              '1.4.8'
gem 'data_mapper',          '1.2.0' ###Evita que nosotros escribamos con código SQL que es el que consulta a la base de datos.
gem 'dm-sqlite-adapter',    '1.2.0'
gem 'json',                 '1.8.6'
gem 'shotgun',              '0.9.2' #Mantiene el server prendido
gem 'slim',                 '3.0.8'
gem 'thin',                 '1.7.0' #Gema utilizada para prender el server
